server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codenavi-db?serverTimezone=Asia/Seoul?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
      show-sql: true
      format-sql: true
    hibernate:
      ddl-auto: create-drop

  # Spring Security 삭제했습니다
  # 개발하면서 삭제하시면 됩니다 ><
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
