spring:
  datasource:
    password: '1234'
  # --- 이메일(SMTP) 설정 ---
  mail:
    host: smtp.gmail.com # 예: Gmail SMTP 서버
    port: 587
    username: retsbe13@gmail.com # 실제 이메일 계정
    password: adthafbclyixvsiy # 이메일 계정 비밀번호 또는 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # --- Redis 설정 ---
  data:
    redis:
      host: localhost
      port: 6379

app:
  jwtSecret: 'VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCBhdXRoZW50aWNhdGlvbiB3aGljaCBzaG91bGQgYmUgc3Ryb25nIGFuZCBsb25nLg=='
  jwtExpirationInMs: '3600000'


