server:
  port: 8080

spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codenavi-db?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
      # ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration