server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codenavi-db
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
      show-sql: true
      format-sql: true
    hibernate:
      ddl-auto: create-drop
      # ddl-auto: update

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
